name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies and Verify Versions
        shell: pwsh
        run: |
          Write-Output "Installing required PowerShell modules and tools..."
          # (Dependency installation code here)

      - name: PowerShell Syntax Test
        shell: pwsh
        run: |
          Write-Output "Performing syntax check for module files..."
          # (Syntax testing code here)

      - name: Lint Testing with PSScriptAnalyzer
        shell: pwsh
        run: |
          Write-Output "Running PSScriptAnalyzer linting..."
          # (Linting code here)

      - name: Run Pester Tests with Code Coverage and Output Test Results
        shell: pwsh
        run: |
          Write-Output "Running Pester tests with code coverage and outputting test results..."
          $configuration = New-PesterConfiguration
          $configuration.Run.Path = "$PWD\Tests"
          $configuration.CodeCoverage.Enabled = $true
          $configuration.CodeCoverage.Path = "$PWD\ZipFileSplitter.psm1"
          $configuration.CodeCoverage.OutputFormat = 'Cobertura'
          $configuration.CodeCoverage.OutputPath = "$PWD\coverage.xml"
          $configuration.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $configuration -Output NUnitXml -OutputFile "$PWD\junit.xml"

      - name: Generate Code Coverage Report
        shell: pwsh
        run: |
          Write-Output "Generating HTML code coverage report..."
          reportgenerator -reports:"$PWD\coverage.xml" -targetdir:"$PWD\coverage-report" -reporttypes:"HtmlInline_AzurePipelines" -title:"Code Coverage Report"

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Coverage-Report
          path: coverage-report/

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
