name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies and Verify Versions
        shell: pwsh
        run: |
          Write-Output "Installing required PowerShell modules..."

          # Check if Pester is installed, and verify its version
          $pesterModule = Get-Module -ListAvailable -Name Pester | Sort-Object Version -Descending | Select-Object -First 1
          if ($null -eq $pesterModule) {
              Write-Output "Pester is not installed, installing Pester..."
              Install-Module -Name Pester -Force -Scope CurrentUser
              $pesterModule = Get-Module -ListAvailable -Name Pester | Sort-Object Version -Descending | Select-Object -First 1
          }
          Write-Output "Using Pester version $($pesterModule.Version)"

          # Check if PSScriptAnalyzer is installed, and verify its version
          $pssaModule = Get-Module -ListAvailable -Name PSScriptAnalyzer | Sort-Object Version -Descending | Select-Object -First 1
          if ($null -eq $pssaModule) {
              Write-Output "PSScriptAnalyzer is not installed, installing PSScriptAnalyzer..."
              Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
              $pssaModule = Get-Module -ListAvailable -Name PSScriptAnalyzer | Sort-Object Version -Descending | Select-Object -First 1
          }
          Write-Output "Using PSScriptAnalyzer version $($pssaModule.Version)"
          Write-Output "Dependencies installed."

      - name: PowerShell Syntax Test
        shell: pwsh
        run: |
          Write-Output "Performing syntax check for module files..."
          Get-ChildItem -Path .\*.psm1 -Recurse | ForEach-Object {
            $syntaxErrors = $null
            $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content -Path $_.FullName -Raw), [ref]$syntaxErrors)
            if ($syntaxErrors.Count -gt 0) {
              $syntaxErrors | ForEach-Object { Write-Host "Syntax error in file $($_.File): Line $($_.StartLine) - $($_.Message)" }
              throw "Syntax check failed."
            }
          }
          Write-Output "Syntax check passed."

      - name: Lint Testing with PSScriptAnalyzer
        shell: pwsh
        run: |
          Write-Output "Running PSScriptAnalyzer linting..."
          $results = Invoke-ScriptAnalyzer -Path "$PWD\ZipFileSplitter.psm1" -Recurse -Severity Warning, Error
          if ($results.Count -gt 0) {
              Write-Output "PSScriptAnalyzer found issues:"
              $results | Format-Table -AutoSize
              throw "Linting failed."
          }
          else {
              Write-Output "No linting issues found."
          }

      - name: Run Pester Tests with Code Coverage
        shell: pwsh
        run: |
          Write-Output "Running Pester tests with code coverage..."
          # Generate coverage data and output it to coverage.xml (without -Output Detailed)
          Invoke-Pester -Script "$PWD\Tests" -CodeCoverage "$PWD\coverage.xml"  

      - name: Generate Code Coverage Report
        shell: pwsh
        run: |
          Write-Output "Generating HTML code coverage report..."
          # Ensure ReportGenerator is installed
          if (-not (Get-Command ReportGenerator -ErrorAction SilentlyContinue)) {
            Write-Output "ReportGenerator not found, installing ReportGenerator..."
            Install-Module -Name ReportGenerator -Force -Scope CurrentUser
          }
          ReportGenerator -reports:"$PWD\coverage.xml" -targetdir:"$PWD\coverage-report"

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Coverage-Report
          path: coverage-report/
